file_object = open('Data-Mining\\HW 00\\HW_00_Raina_Nikhil\\HW_00_NR_Trained.py', 'wt')
file_object.write('from datetime import datetime'+'\n')
file_object.write('import csv'+'\n')
file_object.write(''+'\n')
file_object.write(''+'\n')
file_object.write('def print_name():'+'\n')
file_object.write('  print(\'Nikhil Raina\')'+'\n')
file_object.write('  return'+'\n')
file_object.write(''+'\n')
file_object.write(''+'\n')
file_object.write('def personal_info():'+'\n')
file_object.write('  print(\'I like to act\')'+'\n')
file_object.write('  return'+'\n')
file_object.write(''+'\n')
file_object.write('def created_at():'+'\n')
file_object.write('  print(\'This file was created at 2020-08-27 18:25:34.035377\')'+'\n')
file_object.write('  return'+'\n')
file_object.write(''+'\n')
file_object.write(''+'\n')
file_object.write('def todays_date():'+'\n')
file_object.write('  print(\'Current Date and Time:\', datetime.now().strftime("%d/%m/%Y %H:%M:%S"))'+'\n')
file_object.write('  return'+'\n')
file_object.write(''+'\n')
file_object.write(''+'\n')
file_object.write('def read_and_print_csv_file():'+'\n')
file_object.write('  file = open(\'Data-Mining\\\\HW 00\\\\A_DATA_FILE.csv\')'+'\n')
file_object.write('  csv_reader = csv.reader(file, delimiter=\',\')'+'\n')
file_object.write('  row_counter = 0'+'\n')
file_object.write('  column_counter = 0'+'\n')
file_object.write('  column_counter_flag = True'+'\n')
file_object.write('  header_str = \'HeaderForCol\''+'\n')
file_object.write('  for row_data_set in csv_reader:'+'\n')
file_object.write('    if len(row_data_set) > 0:'+'\n')
file_object.write('      if header_str not in row_data_set[0]:'+'\n')
file_object.write('        for cell in row_data_set:'+'\n')
file_object.write('          if len(cell) > 0:'+'\n')
file_object.write('              if cell.strip() != \' \':'+'\n')
file_object.write('                if(column_counter_flag):'+'\n')
file_object.write('                  column_counter += 1'+'\n')
file_object.write('        column_counter_flag = False'+'\n')
file_object.write('        row_counter += 1'+'\n')
file_object.write('  '+'\n')
file_object.write('  print(\'columns:\', column_counter)'+'\n')
file_object.write('  print(\'rows:\', row_counter)'+'\n')
file_object.write('  file.close()'+'\n')
file_object.write('  return'+'\n')
file_object.write(''+'\n')
file_object.write(''+'\n')
file_object.write('if __name__ == "__main__":'+'\n')
file_object.write('  print_name()'+'\n')
file_object.write('  personal_info()'+'\n')
file_object.write('  created_at()'+'\n')
file_object.write('  todays_date()'+'\n')
file_object.write('  read_and_print_csv_file()'+'\n')
file_object.close()